using System.Collections.Generic;using HeroDefense.Build;using UnityEngine;using UnityEngine.SceneManagement;
namespace HeroDefense.Logging
{
    public enum GameLogLevel{Debug,Info,Warning,Error,Critical}public enum LogCategory{Core,Save,Combat,UI,Build,Audio,Performance}public interface ILogSink{void Write(GameLogLevel level,LogCategory category,string message);}
    public sealed class UnityConsoleLogSink:ILogSink{public void Write(GameLogLevel level,LogCategory category,string message){string value=$"[{category}] {message}";if(level>=GameLogLevel.Error)UnityEngine.Debug.LogError(value);else if(level==GameLogLevel.Warning)UnityEngine.Debug.LogWarning(value);else UnityEngine.Debug.Log(value);}}
    public static class GameLogger{private static readonly List<ILogSink>sinks=new(){new UnityConsoleLogSink()};public static GameLogLevel MinimumLevel=>BuildEnvironmentService.BuildType<=HeroDefenseBuildType.InternalTest?GameLogLevel.Debug:GameLogLevel.Warning;public static void AddSink(ILogSink sink){if(sink!=null&&!sinks.Contains(sink))sinks.Add(sink);}public static void RemoveSink(ILogSink sink)=>sinks.Remove(sink);public static void Log(GameLogLevel level,LogCategory category,string message){if(level<MinimumLevel||string.IsNullOrEmpty(message))return;for(int i=0;i<sinks.Count;i++)sinks[i].Write(level,category,message);}}
    public readonly struct CrashContext{public readonly string Scene,Version,LastSave,RecentError;public CrashContext(string scene,string version,string save,string error){Scene=scene;Version=version;LastSave=save;RecentError=error;}}
    public static class CrashContextProvider{private static string recentError="";public static void RecordError(string summary){recentError=string.IsNullOrEmpty(summary)?"":summary.Substring(0,Mathf.Min(180,summary.Length));}public static CrashContext Capture()=>new(SceneManager.GetActiveScene().name,GameVersionService.DisplayVersion,HeroDefense.Save.SaveGameManager.Instance?.Data?.profile?.lastPlayedAtUtc??"unknown",recentError);}
}
