using UnityEngine;
using UnityEngine.UI;
using HeroDefense.Save;
using HeroDefense.Audio;
using HeroDefense.Accessibility;

namespace HeroDefense.UI
{
    /// <summary>Creates and retains Phase 1 runtime-only preferences.</summary>
    public sealed class SettingsPanelController
    {
        public float MasterVolume => SaveGameManager.Instance?.Data.settings.masterVolume??1f;
        public bool VibrationEnabled => SaveGameManager.Instance?.Data.settings.vibration??true;
        public GameObject Root { get; }

        public SettingsPanelController(Transform parent)
        {
            Root = UiFactory.Panel(parent, "SettingsPanel", new Color(0, 0, 0, .82f), new Vector2(.25f, .16f), new Vector2(.75f, .84f)).gameObject;
            var viewport=new GameObject("Viewport",typeof(RectTransform),typeof(Image),typeof(Mask));viewport.transform.SetParent(Root.transform,false);var viewportRect=viewport.GetComponent<RectTransform>();UiFactory.Stretch(viewportRect,new Vector2(.08f,.06f),new Vector2(.92f,.94f));viewport.GetComponent<Image>().color=new Color(0,0,0,.08f);viewport.GetComponent<Mask>().showMaskGraphic=false;var column=UiFactory.Vertical(viewport.transform,"SettingsContent",12);column.anchorMin=new Vector2(0,1);column.anchorMax=new Vector2(1,1);column.pivot=new Vector2(.5f,1);column.sizeDelta=Vector2.zero;var fitter=column.gameObject.AddComponent<ContentSizeFitter>();fitter.verticalFit=ContentSizeFitter.FitMode.PreferredSize;var scroll=Root.AddComponent<ScrollRect>();scroll.viewport=viewportRect;scroll.content=column;scroll.horizontal=false;scroll.vertical=true;
            UiFactory.Label(column, "Title", "설정", 48, TextAnchor.MiddleCenter, Color.white).gameObject.AddComponent<LayoutElement>().preferredHeight = 90;
            UiFactory.Label(column, "VolumeLabel", "전체 음량", 30, TextAnchor.MiddleLeft, Color.white).gameObject.AddComponent<LayoutElement>().preferredHeight = 55;
            var sliderObject = new GameObject("MasterVolume", typeof(RectTransform), typeof(Image), typeof(Slider), typeof(LayoutElement)); sliderObject.transform.SetParent(column, false);
            sliderObject.GetComponent<Image>().color = new Color(.18f, .24f, .32f);
            var slider = sliderObject.GetComponent<Slider>(); slider.minValue = 0; slider.maxValue = 1; slider.value = MasterVolume; slider.targetGraphic = sliderObject.GetComponent<Image>(); slider.onValueChanged.AddListener(v => {if(SaveGameManager.Instance==null)return;SaveGameManager.Instance.Data.settings.masterVolume=v;SaveGameManager.Instance.ApplySettings();SaveGameManager.Instance.NotifyChanged(SaveReason.SettingsChanged);});
            sliderObject.GetComponent<LayoutElement>().preferredHeight = 65;
            var musicObject=new GameObject("MusicVolume",typeof(RectTransform),typeof(Image),typeof(Slider),typeof(LayoutElement));musicObject.transform.SetParent(column,false);musicObject.GetComponent<Image>().color=new Color(.18f,.24f,.32f);var music=musicObject.GetComponent<Slider>();music.minValue=0;music.maxValue=1;music.value=SaveGameManager.Instance?.Data.settings.musicVolume??.8f;music.targetGraphic=musicObject.GetComponent<Image>();music.onValueChanged.AddListener(v=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.musicVolume=v;AudioManager.Instance?.ApplySettings();save.NotifyChanged(SaveReason.SettingsChanged);});musicObject.GetComponent<LayoutElement>().preferredHeight=48;UiFactory.Label(musicObject.transform,"Label","음악",22,TextAnchor.MiddleLeft,Color.white).raycastTarget=false;
            var sfxObject=new GameObject("SfxVolume",typeof(RectTransform),typeof(Image),typeof(Slider),typeof(LayoutElement));sfxObject.transform.SetParent(column,false);sfxObject.GetComponent<Image>().color=new Color(.18f,.24f,.32f);var sfx=sfxObject.GetComponent<Slider>();sfx.minValue=0;sfx.maxValue=1;sfx.value=SaveGameManager.Instance?.Data.settings.sfxVolume??.9f;sfx.targetGraphic=sfxObject.GetComponent<Image>();sfx.onValueChanged.AddListener(v=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.sfxVolume=v;save.NotifyChanged(SaveReason.SettingsChanged);});sfxObject.GetComponent<LayoutElement>().preferredHeight=48;UiFactory.Label(sfxObject.transform,"Label","효과음",22,TextAnchor.MiddleLeft,Color.white).raycastTarget=false;
            var toggleObject = new GameObject("Vibration", typeof(RectTransform), typeof(Image), typeof(Toggle), typeof(LayoutElement)); toggleObject.transform.SetParent(column, false);
            toggleObject.GetComponent<Image>().color = new Color(.18f, .24f, .32f);
            var toggle = toggleObject.GetComponent<Toggle>(); toggle.isOn = VibrationEnabled; toggle.targetGraphic = toggleObject.GetComponent<Image>(); toggle.onValueChanged.AddListener(v => {if(SaveGameManager.Instance==null)return;SaveGameManager.Instance.Data.settings.vibration=v;SaveGameManager.Instance.NotifyChanged(SaveReason.SettingsChanged);});
            UiFactory.Label(toggleObject.transform, "Label", "진동 활성화 (체크: 켜짐)", 28, TextAnchor.MiddleCenter, Color.white);
            toggleObject.GetComponent<LayoutElement>().preferredHeight = 70;
            var frame=UiFactory.Button(column,"FrameRate",$"목표 프레임: {(SaveGameManager.Instance?.Data.settings.targetFrameRate??60)}",new Color(.2f,.32f,.44f));frame.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.targetFrameRate=save.Data.settings.targetFrameRate==60?30:60;frame.GetComponentInChildren<Text>().text=$"목표 프레임: {save.Data.settings.targetFrameRate}";save.ApplySettings();save.NotifyChanged(SaveReason.SettingsChanged);});
            var quality=UiFactory.Button(column,"GraphicsQuality",$"그래픽: {SaveGameManager.Instance?.Data.settings.graphicsQuality}",new Color(.2f,.32f,.44f));quality.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.graphicsQuality=(GraphicsQualityOption)(((int)save.Data.settings.graphicsQuality+1)%3);quality.GetComponentInChildren<Text>().text=$"그래픽: {save.Data.settings.graphicsQuality}";save.ApplySettings();save.NotifyChanged(SaveReason.SettingsChanged);});
            var language=UiFactory.Button(column,"Language",$"언어: {SaveGameManager.Instance?.Data.settings.language}",new Color(.2f,.32f,.44f));language.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.language=save.Data.settings.language==LanguageOption.Korean?LanguageOption.English:LanguageOption.Korean;language.GetComponentInChildren<Text>().text=$"언어: {save.Data.settings.language}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var shake=UiFactory.Button(column,"ScreenShake",$"화면 흔들림: {(SaveGameManager.Instance?.Data.settings.screenShake==true?"ON":"OFF")}",new Color(.25f,.3f,.38f));shake.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.screenShake=!save.Data.settings.screenShake;shake.GetComponentInChildren<Text>().text=$"화면 흔들림: {(save.Data.settings.screenShake?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var numbers=UiFactory.Button(column,"DamageNumbers",$"데미지 숫자: {(SaveGameManager.Instance?.Data.settings.damageNumbers==true?"ON":"OFF")}",new Color(.25f,.3f,.38f));numbers.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.damageNumbers=!save.Data.settings.damageNumbers;numbers.GetComponentInChildren<Text>().text=$"데미지 숫자: {(save.Data.settings.damageNumbers?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var bars=UiFactory.Button(column,"HealthBars",$"체력바: {(SaveGameManager.Instance?.Data.settings.healthBars==true?"ON":"OFF")}",new Color(.25f,.3f,.38f));bars.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.healthBars=!save.Data.settings.healthBars;bars.GetComponentInChildren<Text>().text=$"체력바: {(save.Data.settings.healthBars?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var large=UiFactory.Button(column,"LargeUi",$"큰 UI: {(SaveGameManager.Instance?.Data.settings.largeUi==true?"ON":"OFF")}",new Color(.25f,.3f,.38f));large.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.largeUi=!save.Data.settings.largeUi;large.GetComponentInChildren<Text>().text=$"큰 UI: {(save.Data.settings.largeUi?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);AccessibilitySettingsService.Apply();});
            var contrast=UiFactory.Button(column,"HighContrast",$"고대비 UI: {(SaveGameManager.Instance?.Data.settings.highContrast==true?"ON":"OFF")}",new Color(.16f,.16f,.16f));contrast.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.highContrast=!save.Data.settings.highContrast;contrast.GetComponentInChildren<Text>().text=$"고대비 UI: {(save.Data.settings.highContrast?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var labels=UiFactory.Button(column,"ColorAccessibility",$"상태 텍스트 표시: {(SaveGameManager.Instance?.Data.settings.colorAccessibility!=false?"ON":"OFF")}",new Color(.25f,.3f,.38f));labels.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.colorAccessibility=!save.Data.settings.colorAccessibility;labels.GetComponentInChildren<Text>().text=$"상태 텍스트 표시: {(save.Data.settings.colorAccessibility?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var aiming=UiFactory.Button(column,"AimAssist",$"스킬 조준 보조: {(SaveGameManager.Instance?.Data.settings.aimAssist!=false?"ON":"OFF")}",new Color(.25f,.3f,.38f));aiming.onClick.AddListener(()=>{var save=SaveGameManager.Instance;if(save==null)return;save.Data.settings.aimAssist=!save.Data.settings.aimAssist;aiming.GetComponentInChildren<Text>().text=$"스킬 조준 보조: {(save.Data.settings.aimAssist?"ON":"OFF")}";save.NotifyChanged(SaveReason.SettingsChanged);});
            var reset=UiFactory.Button(column,"ResetTutorial","튜토리얼 다시 보기",new Color(.32f,.3f,.18f));reset.onClick.AddListener(()=>{var manager=Object.FindAnyObjectByType<HeroDefense.Tutorial.TutorialManager>();if(manager!=null)manager.Restart();});
            UiFactory.Button(column, "Close", "닫기", new Color(.25f, .35f, .55f)).onClick.AddListener(() => Root.SetActive(false));
            Root.SetActive(false);
        }
    }
}
