using HeroDefense.Core;
using HeroDefense.Meta;
using HeroDefense.Save;
using UnityEngine;
using UnityEngine.UI;

namespace HeroDefense.UI.Meta
{
    public static class MetaMenuPanels
    {
        public static GameObject Research(Transform parent){var root=Panel(parent,"ResearchPanel","지휘관 연구");var column=root.transform.Find("Column");var service=new MetaUpgradeService(SaveGameManager.Instance);foreach(var item in MetaUpgradeCatalog.All){var captured=item;var button=UiFactory.Button(column,item.Id,$"{item.Name} Lv.{service.Level(item.Id)}/{item.MaxLevel} | {MetaUpgradeCatalog.Cost(item,service.Level(item.Id))} Coin",new Color(.18f,.36f,.3f));button.onClick.AddListener(()=>{service.TryPurchase(captured.Id);button.GetComponentInChildren<Text>().text=$"{captured.Name} Lv.{service.Level(captured.Id)}/{captured.MaxLevel} | {MetaUpgradeCatalog.Cost(captured,service.Level(captured.Id))} Coin";});}Close(column,root);root.SetActive(false);return root;}
        public static GameObject Collection(Transform parent)
        {
            var root=Panel(parent,"CollectionPanel","도감");var column=root.transform.Find("Column");int discovered=0;foreach(var record in SaveGameManager.Instance.Data.collection)if(record.discovered)discovered++;var summary=UiFactory.Label(column,"Summary",$"발견 {discovered} / {GameContentDatabase.Heroes.Count+GameContentDatabase.Units.Count+GameContentDatabase.Buildings.Count+GameContentDatabase.Stages.Count}",24,TextAnchor.MiddleCenter,Color.white);summary.gameObject.AddComponent<LayoutElement>().preferredHeight=48;
            foreach(var hero in GameContentDatabase.Heroes)AddCollectionRow(column,hero.HeroId,hero.DisplayName,"영웅 · "+hero.RoleName);foreach(var building in GameContentDatabase.Buildings)AddCollectionRow(column,building.BuildingId,building.DisplayName,"건물 · "+building.Description);foreach(var unit in GameContentDatabase.Units)AddCollectionRow(column,unit.UnitId,unit.DisplayName,(unit.Team==HeroDefense.Battle.Combat.Team.Player?"아군":"몬스터")+$" · HP {unit.MaxHealth:0} ATK {unit.AttackDamage:0}");foreach(var stage in GameContentDatabase.Stages)AddCollectionRow(column,stage.StageId,stage.DisplayName,"스테이지 · Wave "+stage.WaveCount);Close(column,root);root.SetActive(false);return root;
        }
        private static void AddCollectionRow(Transform parent,string id,string display,string detail){var record=HeroDefense.Collection.CollectionService.Get(id);bool found=record?.discovered==true;var label=UiFactory.Label(parent,id,found?$"{display} — {detail}\n기록 {record.count}" : "??? — 아직 발견하지 못했습니다.",18,TextAnchor.MiddleLeft,found?Color.white:new Color(.5f,.5f,.55f));label.gameObject.AddComponent<LayoutElement>().preferredHeight=42;}
        public static GameObject Achievements(Transform parent){var root=Panel(parent,"AchievementPanel","업적");var column=root.transform.Find("Column");AchievementService.Evaluate(SaveGameManager.Instance);foreach(var item in AchievementCatalog.All){var captured=item;var record=AchievementService.Get(SaveGameManager.Instance.Data,item.Id);var button=UiFactory.Button(column,item.Id,$"{item.Name} {record.progress}/{item.Target} {(record.claimed?"수령 완료":record.completed?"[보상 수령]":"")}",new Color(.28f,.25f,.42f));button.interactable=record.completed&&!record.claimed;button.onClick.AddListener(()=>{AchievementService.Claim(SaveGameManager.Instance,captured.Id);button.interactable=false;button.GetComponentInChildren<Text>().text=captured.Name+" 수령 완료";});}Close(column,root);root.SetActive(false);return root;}
        public static GameObject ResetConfirmation(Transform parent){var root=UiFactory.Panel(parent,"ResetConfirmation",new Color(0,0,0,.94f),new(.25f,.22f),new(.75f,.78f)).gameObject;var column=UiFactory.Vertical(root.transform,"Column",15);UiFactory.Stretch(column,new(.08f,.08f),new(.92f,.92f));var warning=UiFactory.Label(column,"Warning","모든 진행 기록과 설정을 삭제합니다.\n이 작업은 되돌릴 수 없습니다.",30,TextAnchor.MiddleCenter,Color.white);warning.gameObject.AddComponent<LayoutElement>().preferredHeight=190;var confirm=UiFactory.Button(column,"FirstConfirm","1단계: 초기화 확인",new Color(.5f,.2f,.12f));confirm.onClick.AddListener(()=>{confirm.interactable=false;var final=UiFactory.Button(column,"FinalConfirm","2단계: 정말 초기화",new Color(.7f,.12f,.12f));final.onClick.AddListener(()=>{SaveGameManager.Instance.ResetData();SceneLoader.Instance.Load(SceneNames.MainMenu);});});Close(column,root);root.SetActive(false);return root;}
        private static GameObject Panel(Transform parent,string name,string title)
        {
            var root=UiFactory.Panel(parent,name,new Color(.025f,.045f,.07f,.98f),new(.08f,.05f),new(.92f,.95f)).gameObject;var heading=UiFactory.Label(root.transform,"Title",title,42,TextAnchor.MiddleCenter,UiFactory.Gold);heading.rectTransform.anchorMin=new Vector2(.05f,.89f);heading.rectTransform.anchorMax=new Vector2(.95f,.98f);heading.rectTransform.offsetMin=heading.rectTransform.offsetMax=Vector2.zero;
            var viewport=new GameObject("Viewport",typeof(RectTransform),typeof(Image),typeof(Mask));viewport.transform.SetParent(root.transform,false);var vr=viewport.GetComponent<RectTransform>();UiFactory.Stretch(vr,new Vector2(.04f,.04f),new Vector2(.96f,.88f));viewport.GetComponent<Image>().color=new Color(0,0,0,.15f);viewport.GetComponent<Mask>().showMaskGraphic=false;var column=UiFactory.Vertical(viewport.transform,"Column",8);column.anchorMin=new Vector2(0,1);column.anchorMax=new Vector2(1,1);column.pivot=new Vector2(.5f,1);column.anchoredPosition=Vector2.zero;column.sizeDelta=Vector2.zero;var fitter=column.gameObject.AddComponent<ContentSizeFitter>();fitter.verticalFit=ContentSizeFitter.FitMode.PreferredSize;var scroll=root.AddComponent<ScrollRect>();scroll.viewport=vr;scroll.content=column;scroll.horizontal=false;scroll.vertical=true;scroll.movementType=ScrollRect.MovementType.Clamped;return root;
        }
        private static void Close(Transform column,GameObject root)=>UiFactory.Button(column,"Close","닫기",new Color(.25f,.34f,.5f)).onClick.AddListener(()=>root.SetActive(false));
    }
}
