using System;
using System.Collections;
using System.Collections.Generic;
using HeroDefense.Battle;
using HeroDefense.Battle.Combat;
using HeroDefense.Battle.Effects;
using HeroDefense.Battle.Statistics;
using HeroDefense.Heroes.Skills;
using UnityEngine;
using HeroDefense.Audio;
using UnityEngine.UI;
using HeroDefense.Meta;

namespace HeroDefense.Heroes
{
    /// <summary>Single hero combatant that reuses registry, damage, health, pause, and shared-canvas combat conventions.</summary>
    [RequireComponent(typeof(RectTransform),typeof(HealthComponent))]
    public sealed class HeroController:MonoBehaviour,IAdvancedCombatant
    {
        public event Action<float,float> HealthChanged;public event Action StateChanged;public event Action ResourcesChanged;
        public HeroData Data{get;private set;}public HeroRuntimeState Runtime{get;}=new();public Team Team=>Team.Player;public bool IsAlive=>Runtime.State==HeroState.Alive||Runtime.State==HeroState.CastingSkill||Runtime.State==HeroState.CastingUltimate;public Transform TargetTransform=>transform;public float CollisionRadius=>58;public HealthComponent Health=>health;public IDamageable CurrentTarget=>target;public RuntimeCombatStats RuntimeStats{get;private set;}public StatusEffectController Statuses{get;private set;}public ShieldController Shields{get;private set;}=new();public DamageResult LastDamageResult{get;private set;}
        private CombatRegistry registry;private BattleSessionState session;private PauseController pause;private BattleCombatController combat;private BattleStatistics statistics;private HeroEffectPool effects;private HealthComponent health;private Image body,emotion;private RectTransform bodyRect;private WorldHealthBar worldBar;private IHeroSkillExecutor executor;private IDamageable target;private readonly List<IDamageable> scratch=new(40);private float attackCooldown,targetTimer,selfReduction,selfReductionRemaining,attackSpeedBonus,rangeBonus,buffRemaining,visualAttackKick;private bool pierce,resetting;private int consecutiveHits,emberHits,visualFacing=1;private IDamageable previousTarget;private Vector2 spawnPosition;private Vector3 lastVisualPosition;

        public void Initialize(HeroData data,CombatRegistry valueRegistry,BattleSessionState battleState,PauseController pauseController,BattleCombatController battleCombat,BattleStatistics stats,HeroEffectPool effectPool,Vector2 position)
        {
            Data=data;registry=valueRegistry;session=battleState;pause=pauseController;combat=battleCombat;statistics=stats;effects=effectPool;spawnPosition=position;health=GetComponent<HealthComponent>();RuntimeStats=new RuntimeCombatStats(data.AdvancedStats);Statuses=new StatusEffectController(this);executor=HeroSkillExecutorFactory.Create(data.Archetype);BuildVisual();health.HealthChanged+=OnHealthChanged;health.Damaged+=OnDamaged;health.Died+=OnDied;ResetHero();
        }
        private void BuildVisual()
        {
            var rect=GetComponent<RectTransform>();rect.sizeDelta=Data.FullBodyImage!=null?new Vector2(150,170):Data.VisualShape switch{HeroVisualShape.Knight=>new Vector2(92,140),HeroVisualShape.Ranger=>new Vector2(72,124),_=>new Vector2(82,135)};var bodyObject=new GameObject("AnimatedHeroBody",typeof(RectTransform),typeof(Image));bodyObject.transform.SetParent(transform,false);bodyRect=bodyObject.GetComponent<RectTransform>();bodyRect.sizeDelta=rect.sizeDelta;body=bodyObject.GetComponent<Image>();body.sprite=Data.FullBodyImage;body.preserveAspect=Data.FullBodyImage!=null;body.color=NormalVisualColor;lastVisualPosition=transform.localPosition;
            var label=HeroDefense.UI.UiFactory.Label(transform,"HeroLabel",$"영웅\n{Data.DisplayName}",23,TextAnchor.MiddleCenter,Color.white);label.raycastTarget=false;label.rectTransform.anchorMin=new Vector2(-.2f,-.38f);label.rectTransform.anchorMax=new Vector2(1.2f,0);if(Data.FullBodyImage==null){var weapon=new GameObject("HeroWeapon",typeof(RectTransform),typeof(Image));weapon.transform.SetParent(transform,false);var wr=weapon.GetComponent<RectTransform>();wr.sizeDelta=Data.VisualShape==HeroVisualShape.Knight?new Vector2(18,105):new Vector2(12,82);wr.anchoredPosition=new Vector2(60,0);weapon.GetComponent<Image>().color=Color.Lerp(Data.PlaceholderColor,Color.white,.55f);}var emoteObject=new GameObject("HeroEmotion",typeof(RectTransform),typeof(Image));emoteObject.transform.SetParent(transform,false);emotion=emoteObject.GetComponent<Image>();emotion.raycastTarget=false;emotion.preserveAspect=true;emotion.rectTransform.sizeDelta=new Vector2(72,72);emotion.rectTransform.anchoredPosition=new Vector2(58,112);emotion.gameObject.SetActive(false);worldBar=new WorldHealthBar(transform,new Vector2(0,98),110);
        }
        private void Update()=>Simulate(Time.deltaTime);
        private void LateUpdate()
        {
            if(bodyRect==null||!IsAlive)return;Vector3 current=transform.localPosition;Vector3 delta=current-lastVisualPosition;if(Mathf.Abs(delta.x)>.04f)visualFacing=delta.x>0?1:-1;bool moving=delta.sqrMagnitude>1f;visualAttackKick=Mathf.Max(0,visualAttackKick-Time.deltaTime);float phase=Time.time*8.5f;float bob=moving?Mathf.Abs(Mathf.Sin(phase))*6f:Mathf.Sin(Time.time*2.1f)*1.8f;float lean=moving?Mathf.Sin(phase)*3.2f:Mathf.Sin(Time.time*1.7f);if(visualAttackKick>0){bob+=4;lean=-10f*visualFacing;}bodyRect.anchoredPosition=new Vector2(0,bob);bodyRect.localRotation=Quaternion.Euler(0,0,-lean*visualFacing);float squash=moving?.025f:0;bodyRect.localScale=new Vector3(visualFacing*(1+squash+(visualAttackKick>0?.08f:0)),1-squash,1);lastVisualPosition=current;
        }
        public void Simulate(float dt)
        {
            if(dt<=0||pause.IsPaused||combat.IsStageEnded)return;Statuses.Tick(dt);Shields.Tick(dt);float runtimeDt=IsAlive&&Statuses.IsSilenced?0:dt;if(Runtime.Tick(runtimeDt)){Respawn();return;}if(!IsAlive)return;
            if(selfReductionRemaining>0){selfReductionRemaining=Mathf.Max(0,selfReductionRemaining-dt);if(selfReductionRemaining<=0)selfReduction=0;}if(buffRemaining>0){buffRemaining=Mathf.Max(0,buffRemaining-dt);if(buffRemaining<=0){attackSpeedBonus=rangeBonus=0;pierce=false;}}
            if(Runtime.State!=HeroState.Alive||Statuses.IsStunned||Statuses.IsFrozen)return;attackCooldown=Mathf.Max(0,attackCooldown-dt);targetTimer-=dt;if(target==null||!target.IsAlive||targetTimer<=0){target=Statuses.TauntTarget??registry.FindNearestEnemy(this,Data.DetectionRange);targetTimer=.2f;}
            if(target==null){Move(Vector3.right,dt);return;}Vector3 delta=target.TargetTransform.localPosition-transform.localPosition;float range=(Data.AttackRange*(1+rangeBonus))*CombatUnit.PixelsPerUnit+CollisionRadius+target.CollisionRadius;if(delta.sqrMagnitude>range*range)Move(delta,dt);else TryBasicAttack();
        }
        private void Move(Vector3 direction,float dt){direction.y*=.35f;if(direction.sqrMagnitude>1)direction.Normalize();Vector3 next=transform.localPosition+direction*Data.MoveSpeed*RuntimeStats.MoveSpeedMultiplier*Statuses.MoveMultiplier*CombatUnit.PixelsPerUnit*dt;next.x=Mathf.Min(next.x,610);transform.localPosition=next;}
        private void TryBasicAttack()
        {
            if(attackCooldown>0||target==null||!target.IsAlive)return;attackCooldown=Data.AttackInterval/((1+attackSpeedBonus)*RuntimeStats.AttackSpeedMultiplier*Statuses.AttackSpeedMultiplier);float damage=Data.AttackDamage*RuntimeStats.AttackPowerMultiplier*MetaRuntimeModifierProvider.HeroAttackMultiplier;
            if(Data.Passive.Kind==HeroPassiveKind.ConsecutiveShot){if(previousTarget==target)consecutiveHits++;else{previousTarget=target;consecutiveHits=1;}if(consecutiveHits%3==0)damage*=1.5f;}
            visualAttackKick=.16f;AudioManager.Instance?.PlayEvent(GameAudioEvent.BasicAttack);DealDamage(target,damage,true);effects.Show(transform.localPosition,70,Color.Lerp(Data.PlaceholderColor,Color.white,.3f),.2f);ShowEmotion(true);
            if(Data.Passive.Kind==HeroPassiveKind.Ember){ApplyStatusTo(target,RuntimeStatusCatalog.Get("Burn"),Data.AttackDamage*.1f);if(++emberHits%5==0)DamageArea(target.TargetTransform.localPosition,1.5f,Data.AttackDamage*.4f,6,target);}
            if(pierce)DamageArea(target.TargetTransform.localPosition,2.2f,damage,1,target);
        }
        public bool UseActiveSkill()
        {
            if(pause.IsPaused||combat.IsStageEnded||Statuses.IsSilenced||!Runtime.CanUseSkill||registry.EnemyCount==0)return false;if(!Runtime.BeginSkill(Data.ActiveSkill.Cooldown))return false;if(!executor.ExecuteActive(this)){Runtime.FinishCast();return false;}AudioManager.Instance?.PlayEvent(GameAudioEvent.HeroSkill);statistics.RecordHeroSkillUse();StartCoroutine(FinishCast(Data.ActiveSkill.CastTime));ResourcesChanged?.Invoke();return true;
        }
        public bool UseActiveSkillAt(Vector3 point){if(pause.IsPaused||combat.IsStageEnded||Statuses.IsSilenced||!Runtime.CanUseSkill||registry.EnemyCount==0)return false;if(!Runtime.BeginSkill(Data.ActiveSkill.Cooldown))return false;if(!executor.ExecuteActiveAt(this,ClampSkillPoint(point,Data.ActiveSkill.Range))){Runtime.FinishCast();return false;}AudioManager.Instance?.PlayEvent(GameAudioEvent.HeroSkill);statistics.RecordHeroSkillUse();StartCoroutine(FinishCast(Data.ActiveSkill.CastTime));ResourcesChanged?.Invoke();return true;}
        public bool UseUltimate()
        {
            if(pause.IsPaused||combat.IsStageEnded||Statuses.IsSilenced||!Runtime.CanUseUltimate||registry.EnemyCount==0)return false;if(!Runtime.BeginUltimate())return false;if(!executor.ExecuteUltimate(this)){Runtime.AddEnergy(100);Runtime.FinishCast();return false;}AudioManager.Instance?.PlayEvent(GameAudioEvent.HeroUltimate);statistics.RecordHeroUltimateUse();StartCoroutine(FinishCast(Data.UltimateSkill.CastTime));ResourcesChanged?.Invoke();return true;
        }
        public bool UseUltimateAt(Vector3 point){if(pause.IsPaused||combat.IsStageEnded||Statuses.IsSilenced||!Runtime.CanUseUltimate||registry.EnemyCount==0)return false;if(!Runtime.BeginUltimate())return false;if(!executor.ExecuteUltimateAt(this,ClampSkillPoint(point,Data.UltimateSkill.Range))){Runtime.AddEnergy(100);Runtime.FinishCast();return false;}AudioManager.Instance?.PlayEvent(GameAudioEvent.HeroUltimate);statistics.RecordHeroUltimateUse();StartCoroutine(FinishCast(Data.UltimateSkill.CastTime));ResourcesChanged?.Invoke();return true;}
        public Vector3 ClampSkillPoint(Vector3 point,float range){Vector3 delta=point-transform.localPosition;float max=range*CombatUnit.PixelsPerUnit;return max>0&&delta.sqrMagnitude>max*max?transform.localPosition+delta.normalized*max:point;}
        private IEnumerator FinishCast(float duration){yield return new WaitForSeconds(Mathf.Max(.05f,duration));Runtime.FinishCast();StateChanged?.Invoke();}
        public void TakeDamage(DamageInfo info)=>ApplyAdvancedDamage(info);
        public DamageResult ApplyAdvancedDamage(DamageInfo info)
        {
            if(!IsAlive||Runtime.InvincibilityRemaining>0||info.SourceTeam==Team.Player)return default;float reduction=selfReduction;if(Data.Passive.Kind==HeroPassiveKind.SteelWill&&session.CurrentBaseHp<=session.MaxBaseHp*.5f)reduction=Mathf.Max(reduction,.2f);var adjusted=new DamageInfo(info.Amount*(1-Mathf.Clamp01(reduction)),info.SourceTeam,info.Source,info.DamageType,info.CanCritical,info.CanDodge,info.IsSkill,info.IsUltimate,info.IsDamageOverTime,info.SkillId,info.HitSequence,info.CriticalChanceBonus,info.CriticalDamageBonus,info.ArmorPenetrationFlat,info.ArmorPenetrationPercent,gameObject);LastDamageResult=AdvancedCombatResolver.Apply(this,adjusted);return LastDamageResult;
        }
        public StatusApplyResult ApplyStatus(StatusEffectData data,GameObject source=null,float potency=-1,IDamageable tauntSource=null)=>Statuses.Apply(data,source,potency,tauntSource);
        private void OnDamaged(DamageInfo info){statistics.RecordHeroDamageTaken(info.Amount);Runtime.AddEnergy(Mathf.Min(3,info.Amount*.04f)*MetaRuntimeModifierProvider.UltimateGainMultiplier);ShowEmotion(false);ResourcesChanged?.Invoke();}
        private Color NormalVisualColor=>Data.FullBodyImage!=null?Color.white:Data.PlaceholderColor;
        private void OnDied(DamageInfo info){if(resetting)return;StopAllCoroutines();if(emotion!=null)emotion.gameObject.SetActive(false);registry.Unregister(this);target=null;Runtime.Die(Data.RespawnDuration*MetaRuntimeModifierProvider.HeroRespawnMultiplier);statistics.RecordHeroDeath();Color c=NormalVisualColor;c.a=.25f;body.color=c;transform.localScale=Vector3.one*.35f;StateChanged?.Invoke();}
        private void Respawn(){transform.localPosition=spawnPosition;transform.localScale=Vector3.one;body.color=NormalVisualColor;health.Initialize(EffectiveMaxHealth());target=null;attackCooldown=0;Runtime.Spawn(2f);var invincible=RuntimeStatusCatalog.Get("Invincible");if(invincible!=null)Statuses.Apply(invincible,gameObject);registry.Register(this);statistics.RecordHeroRevive();effects.Show(transform.localPosition,130,new Color(.4f,.9f,1f,.8f),.8f);StateChanged?.Invoke();}
        public void ResetHero(){resetting=true;StopAllCoroutines();if(emotion!=null)emotion.gameObject.SetActive(false);registry?.Unregister(this);Runtime.Reset();RuntimeStats?.Clear();HeroDefense.Progression.BattleModifierRepository.Current?.Apply(RuntimeStats,true);Statuses?.Clear();Shields.Clear();target=null;attackCooldown=targetTimer=selfReduction=selfReductionRemaining=attackSpeedBonus=rangeBonus=buffRemaining=visualAttackKick=0;pierce=false;consecutiveHits=emberHits=0;previousTarget=null;transform.localPosition=spawnPosition;transform.localScale=Vector3.one;if(bodyRect!=null){bodyRect.anchoredPosition=Vector2.zero;bodyRect.localRotation=Quaternion.identity;bodyRect.localScale=Vector3.one;}lastVisualPosition=spawnPosition;body.color=NormalVisualColor;health.Initialize(EffectiveMaxHealth());Runtime.Spawn(2f);registry.Register(this);resetting=false;StateChanged?.Invoke();ResourcesChanged?.Invoke();}
        private float EffectiveMaxHealth()=>Data.MaxHealth*MetaRuntimeModifierProvider.HeroHealthMultiplier;
        public void SetOutcome(bool victory){StopAllCoroutines();target=null;Runtime.SetOutcome(victory);StateChanged?.Invoke();}
        private void OnHealthChanged(float current,float max){worldBar.Set(current,max);HealthChanged?.Invoke(current,max);}
        public void DealSkillDamage(IDamageable value,float amount)=>DealDamage(value,amount,false);
        private void DealDamage(IDamageable value,float amount,bool basic)
        {
            if(value==null||!value.IsAlive)return;bool wasAlive=value.IsAlive;if(value is CombatUnit boss&&boss.Data.UnitId.StartsWith("boss_"))amount*=MetaRuntimeModifierProvider.BossDamageMultiplier;DamageType type=Data.Archetype==HeroArchetype.FireMage?DamageType.Magical:DamageType.Physical;var info=new DamageInfo(amount,Team.Player,gameObject,type,basic,basic,!basic,false,false,basic?"hero_basic":Data.ActiveSkill.SkillId);DamageResult result=value is IAdvancedCombatant advanced?advanced.ApplyAdvancedDamage(info):default;if(!(value is IAdvancedCombatant))value.TakeDamage(info);float actual=result.WasApplied?result.HealthDamage:amount;statistics.RecordHeroDamage(actual);if(result.WasCritical)statistics.RecordCritical(actual);if(!result.WasDodged)Runtime.AddEnergy(basic?2:0);if(value is CombatUnit unit&&unit.Data.UnitId.StartsWith("boss_")&&basic)Runtime.AddEnergy(1);if(wasAlive&&!value.IsAlive){int bonus=value is CombatUnit killed&&killed.Data.UnitId.Contains("elite")?10:5;Runtime.AddEnergy(bonus);statistics.RecordHeroKill();}ResourcesChanged?.Invoke();
        }
        public bool CollectNearHero(float radius,int max,List<IDamageable> output)=>CollectArea(transform.localPosition,radius,max,output,null);
        public bool CollectCone(Vector3 point,float range,float degrees,int max,List<IDamageable> output){registry.CollectEnemies(scratch);output.Clear();Vector3 direction=(point-transform.localPosition).normalized;float minDot=Mathf.Cos(degrees*.5f*Mathf.Deg2Rad);float squared=range*range*CombatUnit.PixelsPerUnit*CombatUnit.PixelsPerUnit;for(int i=0;i<scratch.Count&&output.Count<max;i++){Vector3 delta=scratch[i].TargetTransform.localPosition-transform.localPosition;if(delta.sqrMagnitude<=squared&&Vector3.Dot(direction,delta.normalized)>=minDot)output.Add(scratch[i]);}return output.Count>0;}
        private bool CollectArea(Vector3 center,float radius,int max,List<IDamageable> output,IDamageable excluded)
        {registry.CollectEnemies(scratch);output.Clear();float squared=radius*radius*CombatUnit.PixelsPerUnit*CombatUnit.PixelsPerUnit;for(int i=0;i<scratch.Count&&output.Count<max;i++){IDamageable enemy=scratch[i];if(enemy==excluded)continue;if((enemy.TargetTransform.localPosition-center).sqrMagnitude<=squared)output.Add(enemy);}return output.Count>0;}
        public void DamageArea(Vector3 center,float radius,float damage,int max,IDamageable excluded=null){var targets=new List<IDamageable>(Mathf.Min(max,35));if(!CollectArea(center,radius,max,targets,excluded))return;for(int i=0;i<targets.Count;i++)DealSkillDamage(targets[i],damage);}
        public void ApplyStatusArea(Vector3 center,float radius,StatusEffectData data,float potency,int max){if(data==null)return;var targets=new List<IDamageable>(Mathf.Min(max,35));if(!CollectArea(center,radius,max,targets,null))return;for(int i=0;i<targets.Count;i++)ApplyStatusTo(targets[i],data,potency);}
        public StatusApplyResult ApplyStatusTo(IDamageable value,StatusEffectData data,float potency=-1,IDamageable tauntSource=null){if(value is CombatUnit unit)return unit.ApplyStatus(data,gameObject,potency,tauntSource);if(value is HeroController hero)return hero.ApplyStatus(data,gameObject,potency,tauntSource);return StatusApplyResult.RejectedInvalidTarget;}
        public void DamageMeteor(Vector3 center,float radius,float centerDamage){registry.CollectEnemies(scratch);float outer=radius*CombatUnit.PixelsPerUnit,inner=outer*.45f;float outerSq=outer*outer,innerSq=inner*inner;var burn=RuntimeStatusCatalog.Get("Burn");var stun=RuntimeStatusCatalog.Get("Stun");var slow=RuntimeStatusCatalog.Get("Slow");for(int i=0;i<scratch.Count;i++){var enemy=scratch[i];float sq=(enemy.TargetTransform.localPosition-center).sqrMagnitude;if(sq>outerSq)continue;bool core=sq<=innerSq;float damage=core?centerDamage:centerDamage*.5f;if(enemy is CombatUnit boss&&boss.Data.UnitId.StartsWith("boss_")&&core)damage*=.7f;DealSkillDamage(enemy,damage);ApplyStatusTo(enemy,burn,Data.AttackDamage*.2f);ApplyStatusTo(enemy,core?stun:slow,core?1:.3f);}}
        public void DamageAreaWithBossScale(Vector3 center,float radius,float damage,float bossScale){registry.CollectEnemies(scratch);float squared=radius*radius*CombatUnit.PixelsPerUnit*CombatUnit.PixelsPerUnit;for(int i=0;i<scratch.Count;i++){IDamageable enemy=scratch[i];if((enemy.TargetTransform.localPosition-center).sqrMagnitude>squared)continue;float value=enemy is CombatUnit unit&&unit.Data.UnitId.StartsWith("boss_")?damage*bossScale:damage;DealSkillDamage(enemy,value);}}
        public bool TryFindCrowdedCenter(out Vector3 center,bool bossPriority=false)
        {registry.CollectEnemies(scratch);center=Vector3.zero;if(scratch.Count==0)return false;if(bossPriority)for(int i=0;i<scratch.Count;i++)if(scratch[i] is CombatUnit boss&&boss.Data.UnitId.StartsWith("boss_")){center=boss.TargetTransform.localPosition;return true;}int best=-1,bestCount=-1;float radius=Data.ActiveSkill.Radius*CombatUnit.PixelsPerUnit;float squared=radius*radius;for(int i=0;i<scratch.Count;i++){int count=0;Vector3 p=scratch[i].TargetTransform.localPosition;for(int j=0;j<scratch.Count;j++)if((scratch[j].TargetTransform.localPosition-p).sqrMagnitude<=squared)count++;if(count>bestCount){bestCount=count;best=i;}}center=scratch[best].TargetTransform.localPosition;return true;}
        public void ApplySelfDamageReduction(float amount,float duration){selfReduction=Mathf.Max(selfReduction,amount);selfReductionRemaining=Mathf.Max(selfReductionRemaining,duration);}
        public void ApplyAllyDamageReduction(float amount,float duration){registry.CollectPlayers(scratch);for(int i=0;i<scratch.Count;i++)if(scratch[i] is CombatUnit unit)unit.ApplyDamageReduction(amount,duration);}
        public void ApplyAllyShields(string source,float amount,float duration){registry.CollectPlayers(scratch);for(int i=0;i<scratch.Count;i++)if(scratch[i] is IAdvancedCombatant unit)unit.Shields.Add(source,amount,duration);}
        public void ApplyAttackBuff(float speed,float range,float duration,bool penetrate){attackSpeedBonus=Mathf.Max(attackSpeedBonus,speed);rangeBonus=Mathf.Max(rangeBonus,range);buffRemaining=Mathf.Max(buffRemaining,duration);pierce|=penetrate;}
        public void ShowEffect(Vector3 position,float radius,Color color,float duration=.45f){effects.ShowHero(Data.HeroId,position,radius,color,duration);ShowEmotion(true);}
        private void ShowEmotion(bool happy){if(emotion==null)return;Sprite sprite=HeroDefense.Core.RuntimeArtworkCatalog.HeroEmote(Data.HeroId,happy);if(sprite==null)return;emotion.sprite=sprite;emotion.color=Color.white;emotion.gameObject.SetActive(true);StartCoroutine(HideEmotion());}
        private IEnumerator HideEmotion(){yield return new WaitForSeconds(.8f);if(emotion!=null)emotion.gameObject.SetActive(false);}
        public void StartSkillRoutine(IEnumerator routine)=>StartCoroutine(routine);
        private void OnDestroy(){if(health!=null){health.HealthChanged-=OnHealthChanged;health.Damaged-=OnDamaged;health.Died-=OnDied;}registry?.Unregister(this);}
    }
}
