using System.Collections;
using System.Collections.Generic;
using HeroDefense.Core;
using HeroDefense.Save;
using HeroDefense.UI;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace HeroDefense.Tutorial
{
    public enum TutorialStepType{Message,HighlightUI,WaitForButton,WaitForBuildingPlacement,WaitForUnitProduction,WaitForWaveStart,WaitForSkillUse,WaitForUpgradeSelection,Complete}
    public readonly struct TutorialStep{public readonly string Id,Scene,Target,Message;public readonly TutorialStepType Type;public TutorialStep(string id,string scene,string target,string message,TutorialStepType type=TutorialStepType.WaitForButton){Id=id;Scene=scene;Target=target;Message=message;Type=type;}}
    public sealed class TutorialManager:MonoBehaviour
    {
        private static readonly TutorialStep[] Steps={new("menu_start",SceneNames.MainMenu,"Start","게임 시작 버튼으로 첫 전투를 준비하세요."),new("hero_select",SceneNames.HeroSelect,"hero_arden_knight","영웅 카드를 선택하세요."),new("hero_next",SceneNames.HeroSelect,"StartBattle","스테이지 선택으로 이동하세요."),new("stage_select",SceneNames.StageSelect,"stage_01_grassland","초원의 관문을 선택하세요."),new("stage_start",SceneNames.StageSelect,"Start","전투 시작을 누르세요."),new("battle_barracks",SceneNames.Battle,"building_barracks","병영을 선택하면 빈 건설 슬롯이 강조됩니다."),new("battle_slot",SceneNames.Battle,"BuildSlot_1","강조된 슬롯을 눌러 병영을 건설하세요."),new("battle_wave",SceneNames.Battle,"SkipPreparation","웨이브 HUD에서 준비 시간을 확인할 수 있습니다."),new("battle_skill",SceneNames.Battle,"ActiveSkill","영웅 스킬 버튼은 쿨타임마다 사용할 수 있습니다."),new("battle_pause",SceneNames.Battle,"Pause","본진 HP와 일시정지 버튼을 기억하세요."),new("tutorial_complete",SceneNames.Battle,"Pause","튜토리얼 완료!",TutorialStepType.Complete)};
        private GameObject overlay;private Text message;private Button skip,currentTarget;private readonly List<Button> disabled=new();private int index;private UnityEngine.Events.UnityAction targetAction;
        private void Awake(){DontDestroyOnLoad(gameObject);var canvas=UiFactory.CreateCanvas();canvas.GetComponent<Canvas>().sortingOrder=650;DontDestroyOnLoad(canvas.gameObject);overlay=UiFactory.Panel(canvas,"TutorialOverlay",new Color(0,0,0,.36f),Vector2.zero,Vector2.one).gameObject;overlay.GetComponent<Image>().raycastTarget=false;var box=UiFactory.Panel(overlay.transform,"TutorialMessage",new Color(.03f,.08f,.13f,.97f),new Vector2(.22f,.68f),new Vector2(.78f,.88f));message=UiFactory.Label(box,"Message","",28,TextAnchor.MiddleCenter,Color.white);message.rectTransform.anchorMin=new Vector2(.04f,.12f);message.rectTransform.anchorMax=new Vector2(.78f,.88f);skip=UiFactory.Button(box,"SkipTutorial","건너뛰기",new Color(.45f,.22f,.18f));var rect=skip.GetComponent<RectTransform>();rect.anchorMin=new Vector2(.8f,.18f);rect.anchorMax=new Vector2(.98f,.82f);rect.offsetMin=rect.offsetMax=Vector2.zero;skip.onClick.AddListener(Skip);overlay.SetActive(false);SceneManager.sceneLoaded+=OnSceneLoaded;FindIndex();}
        private void Start(){OnSceneLoaded(SceneManager.GetActiveScene(),LoadSceneMode.Single);}private void FindIndex(){var save=SaveGameManager.Instance?.Data.tutorial;if(save==null)return;if(save.completed||save.skipped){index=Steps.Length;return;}index=0;while(index<Steps.Length&&save.completedSteps.Contains(Steps[index].Id))index++;}
        private void OnSceneLoaded(Scene scene,LoadSceneMode mode){StopAllCoroutines();RestoreButtons();if(index>=Steps.Length||SaveGameManager.Instance?.Data.tutorial.completed==true){overlay.SetActive(false);return;}StartCoroutine(BindWhenReady(scene.name));}
        private IEnumerator BindWhenReady(string scene){yield return null;yield return null;if(index>=Steps.Length||Steps[index].Scene!=scene){overlay.SetActive(false);yield break;}TutorialStep step=Steps[index];GameObject target=null;float timeout=5;while(target==null&&timeout>0){target=GameObject.Find(step.Target);timeout-=Time.unscaledDeltaTime;yield return null;}if(target==null){Debug.LogWarning("Tutorial target missing; skipping safely: "+step.Target);CompleteCurrent();yield break;}currentTarget=target.GetComponent<Button>();if(currentTarget==null){CompleteCurrent();yield break;}message.text=step.Message;overlay.SetActive(true);DisableOtherButtons(currentTarget);targetAction=CompleteCurrent;currentTarget.onClick.AddListener(targetAction);}
        private void DisableOtherButtons(Button allowed){disabled.Clear();var buttons=FindObjectsByType<Button>(FindObjectsInactive.Exclude);for(int i=0;i<buttons.Length;i++){Button button=buttons[i];if(button==allowed||button==skip||!button.interactable)continue;button.interactable=false;disabled.Add(button);}}
        private void RestoreButtons(){if(currentTarget!=null&&targetAction!=null)currentTarget.onClick.RemoveListener(targetAction);for(int i=0;i<disabled.Count;i++)if(disabled[i]!=null)disabled[i].interactable=true;disabled.Clear();currentTarget=null;targetAction=null;}
        private void CompleteCurrent(){RestoreButtons();if(index>=Steps.Length)return;var tutorial=SaveGameManager.Instance.Data.tutorial;if(!tutorial.completedSteps.Contains(Steps[index].Id))tutorial.completedSteps.Add(Steps[index].Id);tutorial.lastStepId=Steps[index].Id;bool complete=Steps[index].Type==TutorialStepType.Complete||++index>=Steps.Length;if(complete)tutorial.completed=true;SaveGameManager.Instance.NotifyChanged();overlay.SetActive(false);if(!complete&&Steps[index].Scene==SceneManager.GetActiveScene().name)StartCoroutine(BindWhenReady(Steps[index].Scene));}
        private void Skip(){RestoreButtons();var tutorial=SaveGameManager.Instance.Data.tutorial;tutorial.skipped=true;tutorial.completed=true;SaveGameManager.Instance.NotifyChanged();index=Steps.Length;overlay.SetActive(false);}
        public void Restart(){var tutorial=SaveGameManager.Instance.Data.tutorial;tutorial.completed=false;tutorial.skipped=false;tutorial.lastStepId="";tutorial.completedSteps.Clear();SaveGameManager.Instance.NotifyChanged();index=0;OnSceneLoaded(SceneManager.GetActiveScene(),LoadSceneMode.Single);}
        private void OnDestroy(){SceneManager.sceneLoaded-=OnSceneLoaded;RestoreButtons();}
    }
}
