namespace HeroDefense.Battle.Statistics
{
    /// <summary>Mutable event-fed stage statistics with an explicit reset boundary.</summary>
    public sealed class BattleStatistics
    {
        public int NormalKills{get;private set;}public int EliteKills{get;private set;}public int BossKills{get;private set;}public int ProducedAllies{get;private set;}public int InstalledBuildings{get;private set;}public int SoldBuildings{get;private set;}public int Upgrades{get;private set;}public int KillGold{get;private set;}public int WaveGold{get;private set;}public float PlayTime{get;private set;}public int ReachedWave{get;private set;}
        public string SelectedHeroId{get;private set;}public float HeroDamageDealt{get;private set;}public float HeroDamageTaken{get;private set;}public int HeroKillCount{get;private set;}public int HeroSkillUseCount{get;private set;}public int HeroUltimateUseCount{get;private set;}public int HeroDeathCount{get;private set;}public int HeroReviveCount{get;private set;}public float HeroHighestSingleHit{get;private set;}
        public float TotalPhysicalDamage{get;private set;}public float TotalMagicalDamage{get;private set;}public float TotalTrueDamage{get;private set;}public int CriticalHitCount{get;private set;}public int DodgedAttackCount{get;private set;}public float ShieldAbsorbedAmount{get;private set;}public float HealingDone{get;private set;}public int StunAppliedCount{get;private set;}public int FreezeAppliedCount{get;private set;}public float BurnDamage{get;private set;}public float PoisonDamage{get;private set;}public int ShockAppliedCount{get;private set;}public int StatusEffectResistedCount{get;private set;}public float HighestCriticalDamage{get;private set;}
        public int BattleLevelReached{get;private set;}=1;public int TotalExperienceEarned{get;private set;}public int UpgradeSelectionCount{get;private set;}public int UpgradeRerollCount{get;private set;}public int CommonUpgradeCount{get;private set;}public int RareUpgradeCount{get;private set;}public int EpicUpgradeCount{get;private set;}public int LegendaryUpgradeCount{get;private set;}
        public int TotalKills=>NormalKills+EliteKills+BossKills;
        public void RecordEnemy(string id,int gold){if(id.StartsWith("boss_"))BossKills++;else if(id.Contains("elite"))EliteKills++;else NormalKills++;KillGold+=gold;}
        public void RecordProduced()=>ProducedAllies++;public void RecordBuilding()=>InstalledBuildings++;public void RecordSale()=>SoldBuildings++;public void RecordUpgrade()=>Upgrades++;public void RecordWaveReward(int gold)=>WaveGold+=gold;public void Tick(float dt)=>PlayTime+=dt>0?dt:0;public void ReachWave(int oneBased)=>ReachedWave=oneBased>ReachedWave?oneBased:ReachedWave;
        public void RecordExperience(int amount,int level){TotalExperienceEarned+=System.Math.Max(0,amount);if(level>BattleLevelReached)BattleLevelReached=level;}public void RecordUpgradeSelection(HeroDefense.Progression.UpgradeRarity rarity,HeroDefense.Progression.UpgradeCategory category){UpgradeSelectionCount++;if(rarity==HeroDefense.Progression.UpgradeRarity.Common)CommonUpgradeCount++;else if(rarity==HeroDefense.Progression.UpgradeRarity.Rare)RareUpgradeCount++;else if(rarity==HeroDefense.Progression.UpgradeRarity.Epic)EpicUpgradeCount++;else LegendaryUpgradeCount++;}public void RecordUpgradeReroll()=>UpgradeRerollCount++;
        public void SelectHero(string id)=>SelectedHeroId=id;public void RecordHeroDamage(float amount){HeroDamageDealt+=amount;if(amount>HeroHighestSingleHit)HeroHighestSingleHit=amount;}public void RecordHeroDamageTaken(float amount)=>HeroDamageTaken+=amount;public void RecordHeroKill()=>HeroKillCount++;public void RecordHeroSkillUse()=>HeroSkillUseCount++;public void RecordHeroUltimateUse()=>HeroUltimateUseCount++;public void RecordHeroDeath()=>HeroDeathCount++;public void RecordHeroRevive()=>HeroReviveCount++;
        public void RecordDamage(HeroDefense.Battle.Combat.DamageType type,float amount){if(type==HeroDefense.Battle.Combat.DamageType.Physical)TotalPhysicalDamage+=amount;else if(type==HeroDefense.Battle.Combat.DamageType.Magical)TotalMagicalDamage+=amount;else TotalTrueDamage+=amount;}public void RecordCritical(float amount){CriticalHitCount++;if(amount>HighestCriticalDamage)HighestCriticalDamage=amount;}public void RecordDodge()=>DodgedAttackCount++;public void RecordShield(float amount)=>ShieldAbsorbedAmount+=amount;public void RecordHealing(float amount)=>HealingDone+=amount;public void RecordStatus(string id,bool resisted=false){if(resisted){StatusEffectResistedCount++;return;}if(id==HeroDefense.Battle.Combat.StatusId.Stun)StunAppliedCount++;else if(id==HeroDefense.Battle.Combat.StatusId.Freeze)FreezeAppliedCount++;else if(id==HeroDefense.Battle.Combat.StatusId.Shock)ShockAppliedCount++;}
        public void Reset(){NormalKills=EliteKills=BossKills=ProducedAllies=InstalledBuildings=SoldBuildings=Upgrades=KillGold=WaveGold=ReachedWave=0;PlayTime=0;SelectedHeroId=null;HeroDamageDealt=HeroDamageTaken=HeroHighestSingleHit=0;HeroKillCount=HeroSkillUseCount=HeroUltimateUseCount=HeroDeathCount=HeroReviveCount=0;TotalPhysicalDamage=TotalMagicalDamage=TotalTrueDamage=ShieldAbsorbedAmount=HealingDone=BurnDamage=PoisonDamage=HighestCriticalDamage=0;CriticalHitCount=DodgedAttackCount=StunAppliedCount=FreezeAppliedCount=ShockAppliedCount=StatusEffectResistedCount=0;}
    }
}
